### ISSUE TITLE
Crash on Flippper v0.166.0

### ISSUE THREAD

**Issue by jabirmhd** [Matju-M/flipper-plugin-basil-ws#3]
Whenever I try to switch between connected web sockets, this plugin crashes.

![image](https://im5.ezgif.com/tmp/ezgif-5-eac15d12fa.gif)

`PLUGIN "BASIL WS (RN)" ENCOUNTERED AN ERROR DURING RENDER
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7BisTrusted%2C%20data%7D for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at vh (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:59291)
    at B (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:64407)
    at wj (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:87758)
    at ll (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:125011)
    at kl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:118004)
    at jl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:117935)
    at Zk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:117794)
    at Vk (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:114849)
    at og (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:49221)
    at gl (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:115155)
    at Nb (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:17011)
    at ld (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:41452)
    at jd (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:25472)
    at id (file:///Applications/Flipper.app/Contents/Resources/app.asar/bundle.js:1213:25260)`

**Comment by mmangion-ys** [comment]
Thanks @jabirmhd. We will try and reproduce and fix the issue!

**Comment by mmangion-ys** [comment]
is it specific for 0.166.0? I have tested 0.146.1 & 0.172.0 and it's working fine.

**Comment by jabirmhd** [comment]
I am still facing this issue in 0.172.0
[![ezgif-1-b3f6f783d9.gif](https://s4.gifyu.com/images/ezgif-1-b3f6f783d9.gif)](https://gifyu.com/image/SEM4l)

**Comment by Matju-M** [comment]
Update to v0.2.9. This should fix the issue.

**Comment by jabirmhd** [comment]
Updating to v0.2.9 fixed the issue. Thanks.
